### ISSUE TITLE
new landing page breaks links 

### ISSUE THREAD

**Issue by cookies1994** [Blathers/neopets-user-scripts#4]
https://www.neopets.com/home/ since world of neopets with the carousell of pets
breaks the quick links
works on other beta pages
but landing page now is https://www.neopets.com/home/ not https://www.neopets.com/  so adds /home/ to all links now and 404s out

**Comment by Blathers** [comment]
Thanks for the feedback I'll look into this tonight!

**Comment by Blathers** [comment]
Fixed in version 1.2
