### ISSUE TITLE
Neopets Add Important Links

### ISSUE THREAD

**Issue by rosemmary** [Blathers/neopets-user-scripts#6]
this script gives navigation errors when trying to use the added links in a sub-land, it adds /faerieland/ to the url for example: https://www.neopets.com/faerieland/inventory.phtml, https://www.neopets.com/winter/quickref /etc.

**Comment by Blathers** [comment]
Thanks for the feedback, this script broke when they updated the site navigation. I'll have to take a look at how it's working now.
