### ISSUE TITLE
Add Important Links appends to a relative path

### ISSUE THREAD

**Issue by PortalInTime** [Blathers/neopets-user-scripts#7]
No clue if I'm using the right terminology there since javascript isn't really my forte, but the gist of the issue is that Add Important Links' sidebar buttons all add onto the currently existing URL, meaning that going to the quickref screen from `neopets.com/home` will lead to `neopets.com/home/quickref.phtml`, which results as an error screen. The easiest way to fix it is to just add the full link to everything that gets passed through `addedLinks`. The inventory link does this, for example, and it works perfectly fine.

**Comment by Blathers** [comment]
Are you up to date with the latest version, this sounds like a repeat of #6 . Can you confirm that you're using version 1.3? Thanks!

**Comment by MPSinclair** [comment]
Still present on 1.3 - just need to prepend the link with a `/`. Line 18 should look like this:

`var linkadd ="<a href=\"/" +link + "\"><li class=\"nav-link-leave-beta__2020\" data-url=\"/" + link + "\"><div class=\"" + icon +"\"></div>" + text +"</li></a>";`

**Comment by Blathers** [comment]
Thanks @MPSinclair ! Should be implemented in 1.4.
